[package]
name = "mdm-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.6", features = ["http2"] }
axum-server = { version = "0.4", features = ["tls-rustls"]}
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
plist = "1"
toml = "0.7"
rusqlite = { version = "0.28", features = ["blob", "uuid"] }
r2d2 = "0.8"
r2d2_sqlite = "0.21"
uuid = { version = "1.3", features = ["serde", "v4"] }
rand = "0.8"
tower = "0.4"
tower-http = { version = "0.3", features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
openssl = "0.10"
optional_value = { path = "./optional_value" }