[package]
name = "mdm-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.5"
serde = { version = "1.0", features = ["derive"] }
plist = "1"
once_cell = "1"
toml = "0.5"
rusqlite = { version = "0.28.0", features = ["blob", "uuid"] }
r2d2 = "0.8"
r2d2_sqlite = "0.21"
uuid = { version = "1.2", features = ["serde", "v4"] }
rand = "0.8"
tower = "0.4"
tower-http = { version = "0.3", features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
