[package]
name = "mdm-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = "0.5"
serde = { version = "1.0", features = ["derive"] }
plist = "1"
