# Welcome to the mdm-server configuration!

[service]
# The address you'd like this service to bind to.
# This can be either an IPv4 or IPv6 address.
# For example, set 0.0.0.0:8080 to listen on all interfaces with port 8080.
# If not specified, defaults to 127.0.0.1:8080.
#
# Format example: 127.0.0.1:8080
bind_address = "127.0.0.1:8080"
# The domain you'd like to use your instance with.
# Please do not include anything beyond the domain.
#
# Format example: mdm.corp.example.com
base_domain = "mdm.corp.example.com"
# Configuration profiles are commonly identified via their identifer
# and a unique UUID. This value is used as the basis.
# It's recommended to use reverse DNS notation for an identifier.
# For example, a SSL certificate may end up with an
# identifier of "com.example.corp.mdm.corporate-ca".
#
# Format example: com.example.corp.mdm
base_identifier = "com.example.corp.mdm"
