[print_schema]
file = "src/database/schema.rs"
# Sure, its location is a little odd, but it helps
# to transform all Timestamps to TimestamptzSqlite.
patch_file = "src/database/schema.patch"

[migrations_directory]
dir = "migrations"
